### ISSUE TITLE
[TESTS] test_browsers_* outcome is timezone-dependent

### ISSUE THREAD

**Issue by sadielbartholomew** [pesos/browser-history#90] opened 2020-10-28 05:32 UTC
Hi, whilst working to complete a PR (for Issue #65) I noticed that the `test_browsers.py` tests were all failing, though all tests passed for `test_generic` and `test_imports`. The errors reported indicate a datetime mismatch and after some investigation, it seems the failures only occur when the tests are run in specific timezones (see the detail, including outputs, provided below). Overall, this seems to imply that either:
1. the datetimes hard-coded into that test fixture are not processed properly to account for any possible timezone of a machine running the tests;
2. there is a timezone-related bug in the datetimes returned in the browser history tuples.

I have not yet determined which of these is the case, if any. I am happy to look into it further, though, assuming it is not obvious to you what the issue is here, and ultimately put in a PR to fix either the tests or the bug (as appropriate) towards hacktoberfest if that is okay? In which case, it would be useful to know if others can recreate these failures by temporarily re-setting the timezone of their machine and running the tests.

# Detail

Note: I am running `browser-history` after installing it in development mode i.e. from the current `master` (via `pip install -e .`).

If I run `pytest` from the root repo directory `browser-history`, I observe the following:

```pytb
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.9.0, pluggy-0.13.1
rootdir: /home/sadie/browser-history
plugins: arraydiff-0.3, doctestplus-0.5.0, openfiles-0.4.0, astropy-header-0.1.2, cov-2.10.1, remotedata-0.3.2, hypothesis-5.24.0
collected 13 items                                                             

tests/test_browsers.py FFFFFFF                                           [ 53%]
tests/test_generic.py .....                                              [ 92%]
tests/test_import.py .                                                   [100%]

=================================== FAILURES ===================================
______________________________ test_firefox_linux ______________________________

become_linux = 'Linux', change_homedir = 'Linux'

    def test_firefox_linux(become_linux, change_homedir):  # noqa: F811
        """Test history is correct on Firefox for Linux"""
        f = browser_history.browsers.Firefox()
        output = f.fetch_history()
        his = output.histories
        assert len(his) == 5
>       assert his[0] == (
            datetime.datetime(
                2020,
                8,
                3,
                0,
                29,
                4,
                tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), "IST"),
            ),
            "https://www.mozilla.org/en-US/privacy/firefox/",
        )
E       AssertionError: assert (datetime.dat...acy/firefox/') == (datetime.dat...acy/firefox/')
E         At index 0 diff: datetime.datetime(2020, 8, 2, 19, 59, 4, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')) != datetime.datetime(2020, 8, 3, 0, 29, 4, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'IST'))
E         Use -v to get the full diff

tests/test_browsers.py:21: AssertionError
______________________________ test_chrome_linux _______________________________

become_linux = 'Linux', change_homedir = 'Linux'

    def test_chrome_linux(become_linux, change_homedir):
        """Test history is correct on Chrome for Linux"""
        f = browser_history.browsers.Chrome()
        output = f.fetch_history()
        his = output.histories
        assert len(his) == 2
>       assert his[0] == (
            datetime.datetime(
                2020,
                10,
                15,
                15,
                34,
                30,
                tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), "CEST"),
            ),
            "www.github.com",
        )
E       AssertionError: assert (datetime.dat...w.github.com') == (datetime.dat...w.github.com')
E         At index 0 diff: datetime.datetime(2020, 10, 15, 14, 34, 30, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')) != datetime.datetime(2020, 10, 15, 15, 34, 30, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'CEST'))
E         Use -v to get the full diff

tests/test_browsers.py:57: AssertionError
_____________________________ test_chromium_linux ______________________________

become_linux = 'Linux', change_homedir = 'Linux'

    def test_chromium_linux(become_linux, change_homedir):
        """Test history is correct on Chromium for Linux"""
        f = browser_history.browsers.Chromium()
        output = f.fetch_history()
        his = output.histories
        assert len(his) == 2
>       assert his[0] == (
            datetime.datetime(
                2020,
                10,
                15,
                15,
                34,
                30,
                tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), "CEST"),
            ),
            "www.github.com",
        )
E       AssertionError: assert (datetime.dat...w.github.com') == (datetime.dat...w.github.com')
E         At index 0 diff: datetime.datetime(2020, 10, 15, 14, 34, 30, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')) != datetime.datetime(2020, 10, 15, 15, 34, 30, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'CEST'))
E         Use -v to get the full diff

tests/test_browsers.py:94: AssertionError
_____________________________ test_firefox_windows _____________________________

become_windows = 'Windows', change_homedir = 'Windows'

    def test_firefox_windows(become_windows, change_homedir):  # noqa: F811
        """Test history is correct on Firefox for Windows"""
        f = browser_history.browsers.Firefox()
        output = f.fetch_history()
        his = output.histories
        assert len(his) == 8
        profs = f.profiles(f.history_file)
        assert len(profs) == 2
        # the history list is long so just check the first and last item
>       assert his[0] == (
            datetime.datetime(
                2020,
                10,
                1,
                11,
                43,
                35,
                tzinfo=datetime.timezone(
                    datetime.timedelta(seconds=10800), "E. Africa Standard Time"
                ),
            ),
            "https://www.youtube.com/",
        )
E       AssertionError: assert (datetime.dat...youtube.com/') == (datetime.dat...youtube.com/')
E         At index 0 diff: datetime.datetime(2020, 10, 1, 9, 43, 35, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')) != datetime.datetime(2020, 10, 1, 11, 43, 35, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800), 'E. Africa Standard Time'))
E         Use -v to get the full diff

tests/test_browsers.py:137: AssertionError
______________________________ test_edge_windows _______________________________

become_windows = 'Windows', change_homedir = 'Windows'

    def test_edge_windows(become_windows, change_homedir):  # noqa: F811
        """Test history is correct for Edge on Windows"""
        e = browser_history.browsers.Edge()
        output = e.fetch_history()
        his = output.histories
        # test history from all profiles
        assert len(his) == 1
>       assert his == [
            (
                datetime.datetime(
                    2020,
                    9,
                    23,
                    10,
                    45,
                    3,
                    tzinfo=datetime.timezone(
                        datetime.timedelta(seconds=19800), "India Standard Time"
                    ),
                ),
                "https://pesos.github.io/",
            ),
        ]
E       AssertionError: assert [(datetime.da....github.io/')] == [(datetime.da....github.io/')]
E         At index 0 diff: (datetime.datetime(2020, 9, 23, 6, 15, 3, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')), 'https://pesos.github.io/') != (datetime.datetime(2020, 9, 23, 10, 45, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'India Standard Time')), 'https://pesos.github.io/')
E         Use -v to get the full diff

tests/test_browsers.py:193: AssertionError
_______________________________ test_safari_mac ________________________________

become_mac = 'Darwin', change_homedir = 'Darwin'

    def test_safari_mac(become_mac, change_homedir):  # noqa: F811
        """Test history is correct for Safari on macOS"""
    
        e = browser_history.browsers.Safari()
        output = e.fetch_history()
        his = output.histories
        assert len(his) == 5
>       assert his[0] == (
            datetime.datetime(
                2020,
                9,
                29,
                23,
                34,
                28,
                tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), "IST"),
            ),
            "https://www.apple.com/in/",
        )
E       AssertionError: assert (datetime.dat...pple.com/in/') == (datetime.dat...pple.com/in/')
E         At index 0 diff: datetime.datetime(2020, 9, 29, 19, 4, 28, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')) != datetime.datetime(2020, 9, 29, 23, 34, 28, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800), 'IST'))
E         Use -v to get the full diff

tests/test_browsers.py:245: AssertionError
______________________________ test_opera_windows ______________________________

become_windows = 'Windows', change_homedir = 'Windows'

    def test_opera_windows(become_windows, change_homedir):
        o = browser_history.browsers.Opera()
        outputs = o.fetch_history()
        his = outputs.histories
        assert len(his) == 2
>       assert his == [
            (
                datetime.datetime(
                    2020,
                    10,
                    13,
                    12,
                    4,
                    51,
                    tzinfo=datetime.timezone(
                        datetime.timedelta(seconds=10800), "E. Africa Standard Time"
                    ),
                ),
                "https://www.youtube.com/",
            ),
            (
                datetime.datetime(
                    2020,
                    10,
                    13,
                    12,
                    4,
                    59,
                    tzinfo=datetime.timezone(
                        datetime.timedelta(seconds=10800), "E. Africa Standard Time"
                    ),
                ),
                "https://github.com/",
            ),
        ]
E       AssertionError: assert [(datetime.da...github.com/')] == [(datetime.da...github.com/')]
E         At index 0 diff: (datetime.datetime(2020, 10, 13, 10, 4, 51, tzinfo=datetime.timezone(datetime.timedelta(0), 'GMT')), 'https://www.youtube.com/') != (datetime.datetime(2020, 10, 13, 12, 4, 51, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800), 'E. Africa Standard Time')), 'https://www.youtube.com/')
E         Use -v to get the full diff

tests/test_browsers.py:277: AssertionError
========================= 7 failed, 6 passed in 0.17s ==========================
```

But I notice that if I change the timezone I have set on my machine via:

```console
$ sudo timedatectl set-timezone America/New_York
```

I then see the tests all pass:

```pytb
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.9.0, pluggy-0.13.1
rootdir: /home/sadie/browser-history
plugins: arraydiff-0.3, doctestplus-0.5.0, openfiles-0.4.0, astropy-header-0.1.2, cov-2.10.1, remotedata-0.3.2, hypothesis-5.24.0
collected 13 items                                                             

tests/test_browsers.py .......                                           [ 53%]
tests/test_generic.py .....                                              [ 92%]
tests/test_import.py .                                                   [100%]

============================== 13 passed in 0.19s ==============================
```

I thought I would try some other timezones out to see which might lead to failures. I found, by changing machine timezone via the equivalent command to the above, that all the `test_browser` tests passed for timezones such as:

* `UTC`
* `Asia/*` for several cities I tried e.g. `Tokyo`, `Calcutta`;

but the following led to varying numbers of failures:

* `Europe`/*` for cities I tried including `London` and `Sofia` (all 7 fail);
* `Pacific/*` e.g . as tested with `Auckland` (2/7 fail);
* `Australia/*` e.g. `Melbourne` (4/7 fail).

Usually but not always the failure `diff` indicated a mismatch between the expected and actual datetimes of one hour so it could be something to do with daylight savings. I am not sure so far. I do however notice that there was a commit message indicating that timezones had been a problem at least on GH Actions (41fee0654d08605513e895f41cb585e9665cd29c) at some point, but that specifically refers to UTC which as I saw was a timezone specification where all the tests passed, and the bug if any, was not present.

**Comment by Samyak2** [comment] 2020-10-29 11:48
Hi. Thank you for the very detailed issue. I appreciate the effort put into this.

>  the datetimes hard-coded into that test fixture are not processed properly to account for any possible timezone of a machine running the tests;

The hard-coded datetimes have a timezone associated with them, which would be the contributor's timezone. I assumed `datetime` would handle all the comparison between datetimes of different timezones which it does, but it seems to not consider DST?

> ultimately put in a PR to fix either the tests or the bug (as appropriate) towards hacktoberfest if that is okay?

Yes, that would be great.

---

I can confirm that setting the timezone to `Europe/London` or `Pacific/Auckland` make the tests fail with the datetime difference being 1 hour
```ipython
In [4]: datetime.datetime(2020, 9, 23, 10, 45, 3, tzinfo=datetime.timezone(datetime.timedelta(seconds=19
   ...: 800), 'India Standard Time')) - datetime.datetime(2020, 9, 23, 17, 15, 3, tzinfo=datetime.timezo
   ...: ne(datetime.timedelta(seconds=46800), 'NZDT'))                                                  
Out[4]: datetime.timedelta(seconds=3600)
```

> I do however notice that there was a commit message indicating that timezones had been a problem at least on GH Actions ([41fee06](https://github.com/pesos/browser-history/commit/41fee0654d08605513e895f41cb585e9665cd29c)) at some point

The issue there was that the hardcoded datetimes did not have timezone information which lead to the test failing under a different timezone. This was fixed in the commit you mentioned.

So far it looks like it arises because of DST because it seems the timezones in which it fails observe DST. (I don't know much of  DST since I don't live in a country which implements DST).

`datetime.tzinfo` implements DST in some way ([reference](https://docs.python.org/3/library/datetime.html#datetime.tzinfo.dst)), but I'm not sure how it's supposed to be used.

**Comment by sadielbartholomew** [comment] 2020-10-29 16:44
Thank you @Samyak2 for your comments and the helpful extra information regarding the issue. (I wouldn't consider it a late response at all, it seemed quick to me so thank you for that.) I have possibly left Hocktobrfest too late this year and if you can't respond in time to the PRs I put in soon that is no problem, I would still like to contribute them regardless as I think this is a great library.

I'll try to get my PRs by tomorrow night latest.

**Comment by Samyak2** [comment] 2020-10-29 19:07
That's great. Thank you!

**Closed** 2020-11-08 09:01 UTC
Labels: bug, hacktoberfest, priority: medium
